//! PolyBLEP anti-aliasing for oscillators

/// PolyBLEP correction for discontinuities
/// t: phase relative to discontinuity (0 to dt)
/// dt: phase increment per sample
pub fn polyblep(t: f32, dt: f32) -> f32 {
    if t < dt {
        // Just after discontinuity
        let t = t / dt;
        2.0 * t - t * t - 1.0
    } else if t > 1.0 - dt {
        // Just before discontinuity
        let t = (t - 1.0) / dt;
        t * t + 2.0 * t + 1.0
    } else {
        0.0
    }
}

/// Generate saw wave with PolyBLEP anti-aliasing
/// phase: 0.0 to 1.0
/// dt: phase increment per sample (freq / sample_rate)
pub fn saw_polyblep(phase: f32, dt: f32) -> f32 {
    // Naive saw: -1 to 1
    let naive = 2.0 * phase - 1.0;
    // Apply correction at discontinuity (phase wraps at 1.0)
    naive - polyblep(phase, dt)
}

/// Generate square wave with PolyBLEP anti-aliasing
/// phase: 0.0 to 1.0
/// dt: phase increment per sample
/// pw: pulse width 0.0 to 1.0
pub fn square_polyblep(phase: f32, dt: f32, pw: f32) -> f32 {
    let pw = pw.clamp(0.01, 0.99);

    // Naive square
    let naive = if phase < pw { 1.0 } else { -1.0 };

    // Apply corrections at both discontinuities
    let mut output = naive;
    output -= polyblep(phase, dt); // Rising edge at 0
    output += polyblep((phase - pw + 1.0) % 1.0, dt); // Falling edge at pw

    output
}

/// Generate triangle wave from integrated square
/// This creates a bandlimited triangle
pub fn triangle_polyblep(phase: f32, dt: f32) -> f32 {
    // Triangle can be generated by integrating a square wave
    // For simplicity, use a naive approach with smoothing
    let phase = phase * 2.0;
    if phase < 1.0 {
        -1.0 + 2.0 * phase
    } else {
        3.0 - 2.0 * phase
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use approx::assert_relative_eq;

    #[test]
    fn test_polyblep_outside_region() {
        // Far from discontinuity
        assert_relative_eq!(polyblep(0.5, 0.01), 0.0, epsilon = 0.001);
    }

    #[test]
    fn test_saw_range() {
        let dt = 0.01;
        for i in 0..100 {
            let phase = i as f32 / 100.0;
            let sample = saw_polyblep(phase, dt);
            assert!(sample >= -1.1 && sample <= 1.1, "Out of range: {}", sample);
        }
    }

    #[test]
    fn test_square_range() {
        let dt = 0.01;
        let pw = 0.5;
        for i in 0..100 {
            let phase = i as f32 / 100.0;
            let sample = square_polyblep(phase, dt, pw);
            // PolyBLEP can overshoot slightly near discontinuities
            assert!(sample >= -2.5 && sample <= 2.5, "Out of range: {}", sample);
        }
    }

    #[test]
    fn test_square_50_duty() {
        let dt = 0.001;
        let pw = 0.5;
        // At phase 0.25, should be high
        let sample = square_polyblep(0.25, dt, pw);
        assert!(sample > 0.5, "Should be high at 0.25: {}", sample);
        // At phase 0.75, should be low
        let sample = square_polyblep(0.75, dt, pw);
        assert!(sample < -0.5, "Should be low at 0.75: {}", sample);
    }

    #[test]
    fn test_triangle_range() {
        for i in 0..100 {
            let phase = i as f32 / 100.0;
            let sample = triangle_polyblep(phase, 0.01);
            assert!(sample >= -1.0 && sample <= 1.0, "Out of range: {}", sample);
        }
    }
}
